// types
// REQUEST
export const ESTADO_REQUEST_EXITO           = 'ESTADO_REQUEST_EXITO'
export const ESTADO_REQUEST_NO_AUTORIZADO   = 'ESTADO_REQUEST_NO_AUTORIZADO'
export const ESTADO_REQUEST_NO_EXISTE       = 'ESTADO_REQUEST_NO_EXISTE'
export const ESTADO_REQUEST_ERROR_SERVIDOR  = 'ESTADO_REQUEST_ERROR_SERVIDOR'
export const ESTADO_REQUEST_DESCONOCIDO     = 'ESTADO_REQUEST_DESCONOCIDO'


// CONTROLES
    // ACCESOS
        // PERMISOS
        export const CONTROLES_ACCESOS_PERMISOS_CARGANDO_TABLA                  = 'CONTROLES_ACCESOS_PERMISOS_CARGANDO_TABLA'
        export const CONTROLES_ACCESOS_PERMISOS_CARGANDO_NUEVO_PERMISO          = 'CONTROLES_ACCESOS_PERMISOS_CARGANDO_NUEVO_PERMISO'
        export const CONTROLES_ACCESOS_PERMISOS_OBTENER_PERMISOS                = 'CONTROLES_ACCESOS_PERMISOS_OBTENER_PERMISOS'
        export const CONTROLES_ACCESOS_PERMISOS_OBTENER_COLUMNAS_TABLA_PERMISOS = 'CONTROLES_ACCESOS_PERMISOS_OBTENER_COLUMNAS_TABLA_PERMISOS'
        export const CONTROLES_ACCESOS_PERMISOS_VISIBILIDAD_MODAL_NUEVO_PERMISO = 'CONTROLES_ACCESOS_PERMISOS_VISIBILIDAD_MODAL_NUEVO_PERMISO'
        
        // TIPOS USUARIOS
        export const CONTROLES_ACCESOS_TIPOS_USUARIOS_CARGANDO_TABLA                        = 'CONTROLES_ACCESOS_TIPOS_USUARIOS_CARGANDO_TABLA'
        export const CONTROLES_ACCESOS_TIPOS_USUARIOS_OBTENER_TIPOS_USUARIOS                = 'CONTROLES_ACCESOS_TIPOS_USUARIOS_OBTENER_TIPOS_USUARIOS'
        export const CONTROLES_ACCESOS_TIPOS_USUARIOS_OBTENER_COLUMNAS_TABLA_TIPOS_USUARIOS = 'CONTROLES_ACCESOS_TIPOS_USUARIOS_OBTENER_COLUMNAS_TABLA_TIPOS_USUARIOS'
        export const CONTROLES_ACCESOS_TIPOS_USUARIOS_VISIBILIDAD_MODAL_NUEVO_TIPO_USUARIO  = 'CONTROLES_ACCESOS_TIPOS_USUARIOS_VISIBILIDAD_MODAL_NUEVO_TIPO_USUARIO'
        export const CONTROLES_ACCESOS_TIPOS_USUARIOS_CARGANDO_NUEVO_TIPO_USUARIO           = 'CONTROLES_ACCESOS_TIPOS_USUARIOS_CARGANDO_NUEVO_TIPO_USUARIO'